apps/crudsurvey/urls.py
from django.conf.urls import url
from apps.crudsurvey.views import SurveCreate, SurveList, SurveDelete, SurveUpdate, SurveShow, search, auth_view, logout, loggedin, invalid_login
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^new/', SurveCreate.as_view(), name='Surve_create'),
    url(r'^list', SurveList.as_view(), name='Surve_list'),
    url(r'^delete/(?P<pk>\w+)/$', SurveDelete.as_view(), name='Surve_eliminate'),
    url(r'^edit/(?P<pk>\w+)/$', SurveUpdate.as_view(), name='Surve_edit'),
    url(r'^show/(?P<pk>\w+)/$', SurveShow.as_view(), name='Surve_show'),
    url(r'^search/$', search, name='Surve_search'),

    # user auth urls
    url(r'^login/$', login, {'template_name':'crudsurvey/login.html'}, name='Login'),
    url(r'^auth/$', auth_view),
    url(r'^logout/$', logout, name='User_logout'),
    url(r'^loggedin/$', loggedin),
    url(r'^invalid/$', invalid_login),

]

survey/urls.py
from django.conf.urls import url, include



urlpatterns = [

    url(r'^survey/', include('apps.crudsurvey.urls', namespace='survey')),


]

website/website/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/crudsurvey/models.py
from django.db import models
 
# Create your models here.


class Surve(models.Model):
    ref_no = models.CharField(primary_key=True, max_length=50)
    house_owner = models.CharField(max_length=50)
    phone_no= models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50)
    latitude = models.CharField(max_length=50)

website/apps/music/models.py
from django.db import models

# Create your models here.

apps/crudsurvey/forms.py
from django import forms
from apps.crudsurvey.models import Surve

class SurveForm(forms.ModelForm):
    class Meta:
        model = Surve
        fields= [
            'ref_no',
            'house_owner',
            'phone_no',
            'longitude',
            'latitude',
        ]

        labels = {
            'ref_no':'Reference Num',
            'house_owner':'House Owners Name',
            'phone_no':'Phone No',
            'longitude':'Longitude',
            'latitude':'Latitude',

        }

        widgets={
            'ref_no': forms.TextInput(attrs={'class':'form-control'}),
            'house_owner': forms.TextInput(attrs={'class':'form-control'}),
            'phone_no': forms.TextInput(attrs={'class':'form-control'}),
            'longitude': forms.TextInput(attrs={'class':'form-control'}),
            'latitude': forms.TextInput(attrs={'class':'form-control'}),

        }

apps/crudsurvey/views.py
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView

from apps.crudsurvey.models import Surve
from apps.crudsurvey.forms import SurveForm
from apps.crudsurvey.filters import SurveFilter

#for login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect
#from django.core.context_processors import csrf
#from django.template.context_processors import csrf
from django.contrib import auth

# Create your views here.
# @login_required(login_url="/survey/login/")
class SurveCreate(CreateView):
    model = Surve
    form_class = SurveForm
    template_name = 'crudsurvey/survey_form.html'
    success_url = reverse_lazy('survey:Surve_list')

class SurveList(ListView):
    queryset = Surve.objects.order_by('ref_no')
    template_name = 'crudsurvey/surve_list.html'
    paginate_by = 4

class SurveUpdate(UpdateView):
    model = Surve
    form_class = SurveForm
    template_name = 'crudsurvey/survey_form.html'
    success_url = reverse_lazy('survey:Surve_list')

class SurveDelete(DeleteView):
    model = Surve
    template_name = 'crudsurvey/surve_delete.html'
    success_url = reverse_lazy('survey:Surve_list')

class SurveShow(DetailView):
    model = Surve
    template_name = 'crudsurvey/surve_show.html'

def search(request):
    Surve_list = Surve.objects.all()
    Surve_filter = SurveFilter(request.GET, queryset=Surve_list)
    return render(request, 'crudsurvey/surve_list2.html', {'filter': Surve_filter})

#for login

@login_required
def login(request):
    return render_to_response('crudsurvey/login.html', {'user': request.user})

def auth_view(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/survey/new')
    else:
        return HttpResponseRedirect('/survey/invalid')

def loggedin(request):
    return render_to_response('crudsurvey/loggedin.html',{'full_name': request.user.username})

def invalid_login(request):
    return render_to_response('crudsurvey/invalid_login.html')

def logout(request):
    auth.logout(request)
    #return HttpResponseRedirect('/')
    return render_to_response('crudsurvey/login.html')

website/apps/music/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% if user.is_authenticated %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
        <!--<img src="{% static "img/nmflogo.png" %}" class="img-responsive" alt="My image"/>-->
		<div class="bs-docs-section clearfix" style="background-image: url('img/nmflogo.png');">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<h3>NEPAL MIND FACTORY</h3>
								<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>

		                  		</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Go To <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'survey:Surve_list' %}">List</a></li>
				                        	<li><a href="{% url 'survey:Surve_search' %}">Search</a></li>
				                        </ul>
		                      		</li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://nepalmindfactory.org/" onclick="pageTracker._link(this.href); return false;">ABOUT US</a>
		                        	</li>
		                        	{% if user.is_authenticated %}
										<li class="dropdown">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Options<span class="caret"></span></a>
											<ul class="dropdown-menu" role="menu">
												<li><a href="{% url 'survey:User_logout' %}">logout</a></li>
											</ul>
										</li>
									{% else %}
										<li class="dropdown">
											<h6>You are not logged in</h6>
										</li>

									{% endif %}
		                    	</ul>
		                    </div>

		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>

	{% endblock %}


	{% block content %}
	<h4>	Blocked contains		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>
{% else %}
	<p>login first</p>
	<p>Click <a href="{% url 'survey:Login' %}">here</a>to login. </p>
{% endif %}

templates/base/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}validation {% endblock %}</title>

</head>
<body>
    {% block content %}
	<h4>	Blocked contains		</h4>
	{% endblock %}

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/crudsurvey/invalid_login.html
<h1>
    Your login details are invalid!
</h1>
{% extends 'base/base.html' %}

templates/crudsurvey/loggedin.html
<h1>
    hi {{full_name}} ur loggedin
    <p>Click <a href="/crudsurvey/logout">here</a>to logout. </p>
</h1>

templates/crudsurvey/login.html
{% extends 'base/base2.html' %}

{% block content %}
<div class="bs-docs-section clearfix" style="background-image: url('img/nmflogo.png');">
   <h1>Welcome!!! You can login here</h1>
    <form action="/survey/auth/" method="post">{% csrf_token %}
        Username:<input name="username" id="username" type="text">
        Password:<input name="password" id="password" type="password">
        <button class="btn btn-info" type="submit">login</button>
    </form>
</div>
{% endblock %}

templates/crudsurvey/surve_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>Are you sure you want to delete this entry? <strong>{{ object.house_owner }}?</strong> </h3>
	<button class="btn btn-danger" type="submit">YES, Delete</button>
	<a class= "btn btn-default" href="{% url 'survey:Surve_list' %}">Cancel</a>
</form>
{% endblock %}

templates/crudsurvey/surve_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>Reference No</td>
			<td>Name of House Owner</td>
			<td>Phone No</td>
			<td>Longitude</td>
			<td>Latitude</td>

		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for surve in object_list %}
		<tr>
			<td>{{ surve.ref_no }}</td>
			<td>{{ surve.house_owner }}</td>
			<td>{{ surve.phone_no }}</td>
			<td>{{ surve.longitude }}</td>
			<td>{{ surve.latitude }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'survey:Surve_show' surve.ref_no %}">View</a>
				<a class="btn btn-primary" href="{% url 'survey:Surve_edit' surve.ref_no %}">Edit</a>
				<a class="btn btn-danger" href="{% url 'survey:Surve_eliminate' surve.ref_no %}">Delete</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No one is registered in survey</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul> 
{% endblock %}

templates/crudsurvey/surve_list2.html
{% extends 'base/base.html' %}

{% block content %}
<h4>Filter by:</h4>
<form method="get">
    <p>
        Ref no: &nbsp{{ filter.form.ref_no }} &nbsp;&nbsp
        House owner: &nbsp{{ filter.form.house_owner }} &nbsp
        Phone: &nbsp {{ filter.form.phone_no }} &nbsp
        <button class="btn btn-success" type="submit">Search</button>
    </p>
</form>
<table class="table table-bordered">
    <thead>
    <tr>
        <td>Reference No</td>
        <td>House owner name</td>
        <td>Phone no</td>
        <td>Longitude</td>
        <td>latitude</td>

    </tr>

    </thead>
    <tbody>
    {% if filter.qs %}
    {% for surve in filter.qs %}
    <tr>
        <td>{{ surve.ref_no }}</td>
        <td>{{ surve.house_owner }}</td>
        <td>{{ surve.phone_no }}</td>
        <td>{{ surve.longitude }}</td>
        <td>{{ surve.latitude }}</td>

        <td>
            <a class="btn btn-primary" href="{% url 'survey:Surve_show' surve.ref_no %}">View</a>
            <a class="btn btn-primary" href="{% url 'survey:Surve_edit' surve.ref_no %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'survey:Surve_eliminate' surve.ref_no %}">Delete</a>
        </td>
    </tr>
    {% endfor %}

    {% else %}
    <h1>No </h1>
    {% endif %}
    </tbody>
</table>
<ul class="pager">
    <li>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
    </li>
    <li>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </li>
</ul>

{% endblock %}

templates/crudsurvey/surve_show.html
{% extends 'base/base.html' %}

{% block content %}

<p><strong>REF No: </strong>{{ object.ref_no }} </p>
<p><strong>House owner's name: </strong>{{ object.house_owner }} </p>
<p><strong>Phone: </strong>{{ object.phone_no }} </p>
<p><strong>Longitude: </strong>{{ object.longitude }} </p>
<p><strong>Latitude: </strong>{{ object.latitude }} </p>

<a class= "btn btn-success" href="{% url 'survey:Surve_list' %}">Ok</a>

{% endblock %}

templates/crudsurvey/survey_form.html
{% extends 'base/base.html' %}

{% block content %}


	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-success" type="submit">Submit</button>
	</form>

{% endblock %}